export const API_ENDPOINT = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
  },
  USER: {
    UPDATE_ME: '/users/me',
    GET_ME: '/users/me',
    GET_BY_ID: '/users/:id',
    UPDATE_TARGET_ROLE: '/users/target-role',
    AVATAR: '/users/me/avatar',
  },
  TARGET_ROLE: {
    GET: 'target-roles',
    CREATE: 'target-roles',
    CREATE_LIST: 'target-roles/bulk',
    GET_ONE: (id: number) => `/target-roles/${id}`,
  },
  MENTOR: {
    UPDATE_PROFILE: '/mentors/me',
    GET_LIST: '/mentors',
    GET_MY_PROFILE: '/mentors/me',
    EXPERIENCES: '/mentors/experiences',
    SKILLS: '/mentors/skills',
    COACHING_PLANS: '/mentor/coaching-plans',
    UPLOAD_INTRODUCTION_VIDEO: '/mentors/upload/introduction-video',
  },
  MENTORS: {
    GET_ALL: '/mentors',
    GET_ONE: (id: number | string) => `/mentors/${id}`,
    GET_AVAILABLE_SLOTS: (id: number | string) => `/mentors/${id}/available-slots`,
  },
  CODE_ENGINE: {
    RUN: '/code-engine/run',
  },
  QUESTIONS: {
    GET_ALL: '/questions',
    GET_RANDOM: '/questions/random',
    GET_ONE: (id: string) => `/questions/${id}`,
  },
  CATEGORIES: {
    GET_ALL: '/categories',
    GET_ONE: (id: number) => `/categories/${id}`,
    CREATE: '/categories',
    UPDATE: (id: number) => `/categories/${id}`,
    DELETE: (id: number) => `/categories/${id}`,
  },
  COMPANIES: {
    GET_ALL: '/companies',
    GET_INDUSTRIES: '/companies/industries',
    GET_ONE: (id: number) => `/companies/${id}`,
    CREATE: '/companies',
    UPDATE: (id: number) => `/companies/${id}`,
    DELETE: (id: number) => `/companies/${id}`,
  },
  JOB_ROLES: {
    GET_ALL: '/job-roles',
    CREATE: '/job-roles',
    UPDATE: (id: number) => `/job-roles/${id}`,
    DELETE: (id: number) => `/job-roles/${id}`,
  },
  MATCHING: {
    JOIN: '/matching/join',
  },
  CODING: {
    GET_ALL: '/coding/questions',
    SUBMIT: '/coding/submit',
    GET_SUBMISSION: (id: number) => `/coding/submission/${id}`,
    GET_QUESTION: (slug: string) => `/coding/question/${slug}`,
  },
  SOLO_RECORDING: {
    UPLOAD_VIDEO: '/solo-recordings/upload-video',
    UPLOAD_AUDIO: '/solo-recordings/upload',
    GET_USER_RECORDINGS: (userId: number | string) => `/solo-recordings/user/${userId}`,
    UPDATE_VIDEO_URL: (recordingId: number) => `/solo-recordings/${recordingId}/video`,
  },
  AI_ANALYSIS: {
    GET_SOLO_RECORDING: (sessionId: number | string) => `/ai-analysis/session/${sessionId}`,
  },
  SLOTS: {
    GET_ALL: '/slots',
    CREATE: '/slots',
    CREATE_BATCH: '/slots/batch',
    UPDATE: (id: number | string) => `/slots/${id}`,
    DELETE: (id: number | string) => `/slots/${id}`,
    DELETE_BATCH: '/slots/batch',
    GET_AVAILABLE_DAYS: (mentorId: number | string) => `/slots/mentors/${mentorId}/available-days`,
    GET_AVAILABLE_SESSIONS: (mentorId: number | string) =>
      `/slots/mentors/${mentorId}/available-sessions`,
  },
  SKILLS: {
    GET_ALL: '/skills',
  },
  COACHING_CATEGORIES: {
    GET_ALL: '/coaching-categories',
    CREATE: '/coaching-categories',
    UPDATE: (id: number) => `/coaching-categories/${id}`,
    DELETE: (id: number) => `/coaching-categories/${id}`,
  },
  PLANS: {
    GET_BY_USER: (userId: number | string) => `/plans/users/${userId}`,
  },
  BOOKING: {
    GET_ALL: '/bookings',
    GET_ONE: (id: number | string) => `/bookings/${id}`,
    CREATE: '/bookings',
    PAY: (id: number | string) => `/bookings/${id}/pay`,
    ACCEPT: (id: number | string) => `/bookings/${id}/accept`,
    REJECT: (id: number | string) => `/bookings/${id}/reject`,
    UPDATE_STATUS: (id: number | string) => `/bookings/${id}/status`,
  },
  FEEDBACK: {
    SUBMIT: (sessionId: number) => `/feedback/session/${sessionId}`,
    MY_FEEDBACK: (sessionId: number) => `/feedback/session/${sessionId}/my`,
    PARTNER_FEEDBACK: (sessionId: number) => `/feedback/session/${sessionId}/partner`,
    PENDING_LIST: '/feedback/pending',
    MY_RECEIVED: '/feedback/my-received',
  },
  CANDIDATE_DASHBOARD: {
    GET_AI_SUMMARY: '/candidate/dashboard/ai-summary',
    GET_ANALYTICS: '/candidate/dashboard/analytics',
    GET_UPCOMING_SESSIONS: '/candidate/dashboard/upcoming-sessions',
    GET_INTERESTED_CATEGORIES: '/candidate/dashboard/interested-categories',
  },
  NOTIFICATIONS: {
    GET_MY: '/notifications',
    MARK_READ: (id: number) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
  },
  SESSION: {
    GET_ALL: '/sessions',
    GET_ONE: (id: number | string) => `/sessions/${id}`,
    UPDATE_MEETING_LINK: (id: number | string) => `/sessions/${id}/meeting-link`,
    ACCEPT: (id: number | string) => `/sessions/${id}/accept`,
    REJECT: (id: number | string) => `/sessions/${id}/reject`,
    CANCEL: (id: number | string) => `/sessions/${id}/cancel`,
  },
  BOOKMARK: {
    GET_ALL: '/users/me/bookmarks',
    BOOKMARK: (questionId: number | string) => `/users/me/bookmarks/${questionId}`,
    UNBOOKMARK: (questionId: number | string) => `/users/me/bookmarks/${questionId}`,
  },
  ADMIN: {
    STATISTICS: '/admin/statistics',
    STATISTICS_GROWTH_CHART: '/admin/statistics/growth-chart',
    STATISTICS_TOP_MENTORS: '/admin/statistics/top-mentors',
    MENTORS: '/admin/mentors',
    MENTOR_DETAIL: (id: number) => `/admin/mentors/${id}`,
    APPROVE_MENTOR: (id: number) => `/admin/mentors/${id}/approve`,
    REJECT_MENTOR: (id: number) => `/admin/mentors/${id}/reject`,
    USERS: '/admin/users',
    USER_DETAIL: (id: number) => `/admin/users/${id}`,
    REPORTED_USERS: '/admin/users/reported',
    BAN_USER: (id: number) => `/admin/users/${id}/ban`,
    UNBAN_USER: (id: number) => `/admin/users/${id}/unban`,
    REPORTS: '/reports',
    REPORT_DETAIL: (id: number) => `/reports/${id}`,
    UPDATE_REPORT_STATUS: (id: number) => `/reports/${id}/status`,

    QUESTIONS: '/admin/questions',
    QUESTION_DETAIL: (id: number) => `/admin/questions/${id}`,
    CREATE_QUESTION: '/admin/questions',
    UPDATE_QUESTION: (id: number) => `/admin/questions/${id}`,
    DELETE_QUESTION: (id: number) => `/admin/questions/${id}`,
    RANDOM_QUESTION: '/admin/questions/random',

    WALLET_TRANSACTIONS: '/admin/wallet/transactions',
    WALLET_STATISTICS: '/admin/wallet/statistics',
    WALLET_ADJUST: (userId: number) => `/admin/wallet/adjust/${userId}`,
    MENTOR_PAYOUTS: '/admin/mentor-payouts',
    APPROVE_MENTOR_PAYOUT: (id: number) => `/admin/mentor-payouts/${id}/approve`,
    REJECT_MENTOR_PAYOUT: (id: number) => `/admin/mentor-payouts/${id}/reject`,
    RETRYABLE_PAYOUTS: '/admin/payout/retryable',
    RETRY_SESSION_PAYOUT: (sessionId: number) => `/admin/payout/retry/${sessionId}`,
  },

  RECOMMENDATIONS: {
    GET_FOR_CANDIDATE: (candidateUserId: number | string) =>
      `/recommendations/candidate/${candidateUserId}`,
  },

  REPORT: {
    CREATE_USER: '/reports/user',
    CREATE_COMMENT: '/reports/comment',
    GET_LIST: '/reports',
    GET_ONE: (id: number) => `/reports/${id}`,
  },
  WALLET: {
    GET_ME: '/wallet/me',
    GET_TRANSACTIONS: '/wallet/transactions',
  },
  PAYMENT: {
    DEPOSIT: '/payment/deposit',
    WEBHOOK_SEPAY: '/payment/webhook/sepay',
    STATUS: (paymentId: number) => `/payment/status/${paymentId}`,
    MOCK_SUCCESS: (paymentId: number) => `/payment/mock/${paymentId}`,
  },
};
